spring:
  application:
    name: user-pro

dubbo:
  application:
    # 应用名称
    name: user-provider1
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 20880
  registry:
    # 注册中心地址
    address: zookeeper://127.0.0.1:2181
  # 服务类包目录
  #scan: com.springboot.service.impl
